In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [2]:
match_path= "Resources/Matches_Results.csv"
odds_path= "Resources/Matches_Odds.csv"

In [3]:
matches=pd.read_csv(match_path)
odds=pd.read_csv(odds_path)

In [4]:
matches.head(10)

,match_id,date_start,competition_name,home_team_name,away_team_name,home_team_score,away_team_score,final_result
0,1,12/26/2016 12:30,Eng. Premier League,Watford,Crystal Palace,1,1,x
1,2,12/26/2016 15:00,Eng. Premier League,Burnley,Middlesbrough,1,0,1
2,3,12/26/2016 15:00,Eng. Premier League,Manchester United,Sunderland,3,1,1
3,4,12/26/2016 15:00,Eng. Premier League,Swansea,West Ham,1,4,2
4,5,12/26/2016 15:00,Eng. Premier League,Arsenal,West Bromwich Albion,1,0,1
5,6,12/26/2016 15:00,Eng. Premier League,Leicester,Everton,0,2,2
6,7,12/26/2016 15:00,Eng. Premier League,Chelsea,Bournemouth,3,0,1
7,8,12/26/2016 17:15,Eng. Premier League,Hull,Manchester City,0,3,2
8,9,12/27/2016 17:15,Eng. Premier League,Liverpool,Stoke,4,1,1
9,10,12/28/2016 19:44,Eng. Premier League,Southampton,Tottenham,1,4,2

In [5]:
merged_df=pd.merge(matches, odds, on=["match_id"])

In [6]:
merged_df=merged_df.drop(columns=["date_start_y"])

In [7]:
merged_df

,match_id,date_start_x,competition_name_x,home_team_name_x,away_team_name_x,home_team_score,away_team_score,final_result,competition_name_y,date_created,home_team_name_y,away_team_name_y,home_team_odd,away_team_odd,tie_odd
0,1,12/26/2016 12:30,Eng. Premier League,Watford,Crystal Palace,1,1,x,Eng. Premier League,12/26/2016 12:00,Watford,Crystal Palace,2.35,3.10,3.10
1,1,12/26/2016 12:30,Eng. Premier League,Watford,Crystal Palace,1,1,x,Eng. Premier League,12/26/2016 6:45,Watford,Crystal Palace,2.40,3.00,3.25
2,1,12/26/2016 12:30,Eng. Premier League,Watford,Crystal Palace,1,1,x,Eng. Premier League,12/26/2016 3:35,Watford,Crystal Palace,2.40,3.10,3.10
3,1,12/26/2016 12:30,Eng. Premier League,Watford,Crystal Palace,1,1,x,Eng. Premier League,12/23/2016 19:45,Watford,Crystal Palace,2.45,2.90,3.25
4,1,12/26/2016 12:30,Eng. Premier League,Watford,Crystal Palace,1,1,x,Eng. Premier League,12/25/2016 15:20,Watford,Crystal Palace,2.45,3.00,3.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466669,844769,5/23/2018 19:44,French Ligue 1 Playoffs,Ajaccio,Toulouse,0,3,2,French Ligue 1 Playoffs,5/23/2018 18:35,Ajaccio,Toulouse,3.60,2.11,3.00
466670,844769,5/23/2018 19:44,French Ligue 1 Playoffs,Ajaccio,Toulouse,0,3,2,French Ligue 1 Playoffs,5/23/2018 18:25,Ajaccio,Toulouse,3.65,2.08,3.00
466671,844769,5/23/2018 19:44,French Ligue 1 Playoffs,Ajaccio,Toulouse,0,3,2,French Ligue 1 Playoffs,5/23/2018 13:35,Ajaccio,Toulouse,3.65,2.10,2.95
466672,844769,5/23/2018 19:44,French Ligue 1 Playoffs,Ajaccio,Toulouse,0,3,2,French Ligue 1 Playoffs,5/23/2018 13:40,Ajaccio,Toulouse,3.75,2.05,3.00
466673,844769,5/23/2018 19:44,French Ligue 1 Playoffs,Ajaccio,Toulouse,0,3,2,French Ligue 1 Playoffs,5/23/2018 18:10,Ajaccio,Toulouse,3.85,2.01,3.00

In [9]:
#grouping the data for just the 5 leagues of interest
#also grouping datapoints of the same match id together

leagues = merged_df.groupby('competition_name_x')

English = leagues.get_group('Eng. Premier League')
German = leagues.get_group('German Bundesliga')
French = leagues.get_group('French Ligue 1')
Spanish = leagues.get_group('Spanish Liga Primera')
Italian = leagues.get_group('Italian Serie A')

eng_matches = English.groupby('match_id')
ger_matches = German.groupby('match_id')
fre_matches = French.groupby('match_id')
spa_matches = Spanish.groupby('match_id')
ita_matches = Italian.groupby('match_id')

eng_matches.head(1)

#print(f"{len(eng_matches)}, {len(ger_matches)}, {len(fre_matches)}, {len(spa_matches)}, {len(ita_matches)}")
#print(f"{len(English)}, {len(German)}, {len(French)}, {len(Spanish)}, {len(Italian)}")

#prints show that we are missing some matches since the leagues had 380 matches each, except the German one with 306
#of interest would be finding out which matches are missing from dataset

,match_id,date_start_x,competition_name_x,home_team_name_x,away_team_name_x,home_team_score,away_team_score,final_result,competition_name_y,date_created,home_team_name_y,away_team_name_y,home_team_odd,away_team_odd,tie_odd
0,1,12/26/2016 12:30,Eng. Premier League,Watford,Crystal Palace,1,1,x,Eng. Premier League,12/26/2016 12:00,Watford,Crystal Palace,2.35,3.10,3.10
8,2,12/26/2016 15:00,Eng. Premier League,Burnley,Middlesbrough,1,0,1,Eng. Premier League,12/26/2016 13:45,Burnley,Middlesbrough,2.75,2.70,3.00
18,3,12/26/2016 15:00,Eng. Premier League,Manchester United,Sunderland,3,1,1,Eng. Premier League,12/26/2016 15:00,Manchester United,Sunderland,1.17,15.00,6.75
30,4,12/26/2016 15:00,Eng. Premier League,Swansea,West Ham,1,4,2,Eng. Premier League,12/26/2016 8:45,Swansea,West Ham,2.20,3.10,3.40
44,5,12/26/2016 15:00,Eng. Premier League,Arsenal,West Bromwich Albion,1,0,1,Eng. Premier League,12/25/2016 13:15,Arsenal,West Bromwich Albion,1.28,10.00,5.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445587,779262,4/14/2018 15:00,Eng. Premier League,Huddersfield,Watford,1,0,1,Eng. Premier League,4/14/2018 9:40,Huddersfield,Watford,2.50,2.85,3.10
446019,779822,4/14/2018 19:44,Eng. Premier League,Tottenham,Manchester City,1,3,2,Eng. Premier League,4/9/2018 6:45,Tottenham,Manchester City,2.40,2.70,3.50
450139,785885,4/21/2018 15:00,Eng. Premier League,Watford,Crystal Palace,0,0,x,Eng. Premier League,4/7/2018 16:05,Watford,Crystal Palace,2.35,3.00,3.20
457004,793088,5/5/2018 17:29,Eng. Premier League,Everton,Southampton,1,1,x,Eng. Premier League,4/22/2018 1:25,Everton,Southampton,2.10,3.50,3.20
457049,793103,5/5/2018 12:30,Eng. Premier League,Stoke,Crystal Palace,1,2,2,Eng. Premier League,5/5/2018 5:20,Stoke,Crystal Palace,2.45,2.80,3.25